Update 5_prototype_analysis.yml

diff --git a/.github/workflows/5_prototype_analysis.yml b/.github/workflows/5_prototype_analysis.yml
--- a/.github/workflows/5_prototype_analysis.yml
+++ b/.github/workflows/5_prototype_analysis.yml
@@ -62,12 +62,28 @@ jobs:
             echo "::error:: Ошибка - в сервисе db не организованы volumes. По заданию они требуются для того, чтобы сохранять данные БД между запусками вашей конфигурации"
             exit 1
           fi
+
+          if yq '.services.db.volumes' ${dc_file} | grep -q '^[^/]*/'
+          then
+            echo "::error:: Ошибка - в сервисе db  volumes использует монтирование каталогов. Используйте вместо этого именно volumes ( https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose) - это гораздо удобнее и позволяет управлять таким хранилищем через докер."
+            exit 1
+          fi
           
           if yq '.network' ${dc_file} | grep -q 'host' ; 
           then
             echo "::error:: Ошибка - сеть типа host. Пожалуйста, не используйте данный тип сети: он максимально небезопасен (так как неглядя мапит все порты вашей конфигурации на адаптер хоста) и неудобен. Укажите вместо этого конкретные маппинги портов в соответствующих директивах ports"
             exit 1
           fi
+
+          # Проверка volumes
+          echo "::info:: Ниже будут все volumes всех сервисов"
+          yq '.services.*.volumes' ${dc_file}
+          if yq '.services.*.volumes' docker-compose.yml | grep -v ':ro$' | grep -q '^[^/]*/'
+          then
+            echo "::error:: Ошибка - у вас есть смонтированные в volumes файлы и/или каталоги без метки ro (read-only, https://docs.docker.com/compose/compose-file/05-services/#short-syntax-5). Монтируемый каталог или файл нужно или копировать на этапе сборки контейнера (если там данные, которые не предполагают изменение), или ставить опцию :ro ."
+            exit 1
+          fi
+          
           
           # Проверка всех сервисов на общие ошибки
           for i in $(seq 0 $(( services_count - 1 )) );
@@ -94,7 +110,7 @@ jobs:
                 echo "::error:: Ошибка - явно не указан интерфейс при маппинге портов. По умолчанию (если не указывать вот так 127.0.0.1:3000:80), докер мапит на все доступные интерфейсы и это нарушает безопасность. Добавьте 127.0.0.1: к содержимому директивы ports "
                 exit 1
               fi
-            fi
+            fi            
           
             external_ports=`echo $ports | grep '127.0.0.1' | sed 's/^[^1]*127.0.0.1:\([^:]*\):[^:]*$/\1/g'`
             for port in $external_ports;
